services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://admin:admin123@db:5432/development?schema=public'
      FOOD_DATA_BASE_URL: 'https://challenges.coode.sh/food/data/json/'
      FOOD_DATA_INDEX_URL: 'https://challenges.coode.sh/food/data/json/index.txt'
      ELASTICSEARCH_HOST: 'http://elasticsearch:9200'
      API_KEY: '4f8b2d7e9c1a4e5f8b2d7e9c1a4e5f8b2d7e9c1a4e5f8b2d7e9c1a4e5f8b2d7e9'
      API_PORT: '3000'
    depends_on:
      - db
      - elasticsearch

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: development
    ports:
      - '5432:5432'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
